use arcm;
TRUNCATE arcm.adjournment;
TRUNCATE arcm.adjournmentdocuments;
--- TRUNCATE arcm.applicants;
TRUNCATE arcm.applicantshistory;
  TRUNCATE arcm.applicationdocuments;
  TRUNCATE arcm.applicationdocumentshistory;
TRUNCATE arcm.applicationfees;
TRUNCATE arcm.applicationfeeshistory;
TRUNCATE arcm.applicationfees;
TRUNCATE arcm.applicationfeeshistory;
TRUNCATE arcm.applications;
TRUNCATE arcm.interestedparties;

  TRUNCATE arcm.applicationshistory ;
  TRUNCATE arcm.applications_approval_workflow;
TRUNCATE arcm.attendanceregister;
TRUNCATE arcm.audittrails;
TRUNCATE arcm.casedetails;
TRUNCATE arcm.casesittingsregister;
TRUNCATE arcm.casewithdrawal;
TRUNCATE arcm.casewithdrawalcontacts;
TRUNCATE arcm.deadlineapprovalworkflow;
TRUNCATE arcm.groundsandrequestedorders;
TRUNCATE arcm.groundsandrequestedordershistory;
TRUNCATE arcm.hearingattachments;
TRUNCATE arcm.hearingnotices;
TRUNCATE arcm.mpesatransactions;
TRUNCATE arcm.notifications;
TRUNCATE arcm.panellist;
TRUNCATE arcm.panels;
TRUNCATE arcm.panelsapprovalworkflow;
TRUNCATE arcm.pedeadlineextensionsrequests;
TRUNCATE arcm.peresponse;
TRUNCATE arcm.peresponsedetails;
TRUNCATE arcm.peresponsedocuments;
TRUNCATE arcm.peresponsetimer;
TRUNCATE arcm.rb1forms;
TRUNCATE arcm.schedules;
TRUNCATE arcm.schedules;
TRUNCATE arcm.tenderaddendums;
Delete FROM arcm.tenders;
TRUNCATE arcm.venuebookings;
TRUNCATE arcm.applicationsequence;
TRUNCATE arcm.paymentdetails;
TRUNCATE arcm.bankslips;
TRUNCATE arcm.feesapprovalworkflow;
TRUNCATE arcm.applications_approval_workflow;
--- TRUNCATE arcm.venues;